language: rust
sudo: enabled
services:
  - docker
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_install:
  - docker run -d -p 3000:3000 juxt/crux-standalone:20.07-1.10.0
script:
    - cargo build
    - cargo test --examples
    - cargo run --example async_tx_log --features "async"
    - cargo run --example async_tx_logs --features "async"
    - cargo run --example async_entity_timed --features "async"
    - cargo run --example async_entity_tx_timed --features "async"
    - cargo run --example async_entity_history_timed --features "async"
    - cargo run --example async_query --features "async"
